disabled_rules:
- colon
- comma
- control_statement
- function_body_length
- cyclomatic_complexity
- trailing_whitespacea

line_length: 120


opt_in_rules:
- empty_count
- missing_docs
- nesting
- force_try/cast/unwrapping
- weak_delegate


excluded:
- Carthage
- Pods
- LufthansaApp/Delegates/AppDelegate.swift
- LufthansaApp/Delegates/SceneDelegate.swift
- Source/ExcludedFolder
- Source/ExcludedFile.swift


reporter: xcode
warning_threshold: 30
